// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    try {
      // Only attempt to get session on the client side
      if (typeof window === 'undefined') {
        return next({ headers: {} })
      }
      
      const { data } = await supabase.auth.getSession()
      const token = data.session?.access_token
      return next({
        headers: token ? { Authorization: `Bearer ${token}` } : {},
      })
    } catch (error) {
      console.warn('[Supabase Auth] Failed to get session:', error)
      // Continue without auth token if Supabase is unavailable
      return next({
        headers: {},
      })
    }
  },
)
